### ISSUE TITLE
 Errors on using SiliCompressor.with(Context).compressVideo(sourceUriString, destinationUriString);

### ISSUE THREAD

**Issue by sonamsamdupkhangsar** [bhaskardonadapti5/SiliCompressor-master#1]

**Comment by Hanumantha-Rao** [comment]
If I pass Uri string then it is getting error to fetch the file path.
If I pass direct file path then also it is giving error while fetching file Utils.getFilePath(uri).

Instead of this please add compressVideo(), can accept direct file path and destination Uri. Instead of again fetching file from Uri.
